### ISSUE TITLE
All menu's under a single root

### ISSUE THREAD

**Issue by solvingj** [KUTlime/PowerShell-Open-Here-Module#10]
I tried this expecting them to all show up under a single root.  Instead, they all created their own duplicate root item called "Prompts".  Can the desired behavior be supported?

```
Set-OpenHereShortcut -ShortcutType:Windowsterminal -RootName 'Prompts' -OpenHere 'Terminal' -OpenHereAsAdmin 'Terminal as Admin'
Set-OpenHereShortcut -ShortcutType:WindowsPowerShell -RootName 'Prompts' -OpenHere 'Powershell' -OpenHereAsAdmin 'Powershell as Admin'
Set-OpenHereShortcut -ShortcutType:CMD -RootName 'Prompts' -OpenHere 'CMD' -OpenHereAsAdmin 'CMD as Admin'
```

**Comment by KUTlime** [comment]
I have to close this issue with the `wontfix` status. As I've already explain in a different [issue](https://github.com/KUTlime/PowerShell-Open-Here-Module/issues/20), during the technical analysis I've found a limitation of Windows that dictates that the can't be more than one Run as command in the context menu or a single subfolder (_single root_).

I could add as many shortcut into the context menu but there could be only one shortcut with elevated privileges.

In order to keep the functionality of this module consistent and a clean code base, I drop this idea to create shortcuts under a single root.

I hope that you still enjoy this module as it is. ✌
