### ISSUE TITLE
Is it possible to create only root executable. So, when I press root itself, it should open Windows terminal here and that's it?

### ISSUE THREAD

**Issue by orzklv** [KUTlime/PowerShell-Open-Here-Module#20]

**Comment by KUTlime** [comment]
Could you elaborate more about this? I'm not sure if I'm getting your point.

**Comment by orzklv** [comment]
So I can see there is a root "Windows Terminal". If I gonna press that "windows terminal" itself, it should just open terminal instead of popping out another context menu

**Comment by KUTlime** [comment]
OK, I know what you mean. 

This will bring a drastic amount of code complexity in the current code base but I will look on it sooner or later. I can't promise any date, I'm dead busy right now.

**Comment by orzklv** [comment]
Ah I got it bro. Thanks btw)

**Comment by ririshi** [comment]
Hey, I have another suggestion close to what @genemators suggested. I'd like to add the open here options to context menus without adding the root folder in between. So for example just having "Windows terminal here" and "Windows terminal admin here" in the context menus. Appreciate your work on this! Lifesaver until Windows Terminal ships with its own proper shell extension.

**Comment by KUTlime** [comment]
Acknowledged!

**Comment by KUTlime** [comment]
Guys, I have to close this issue with the `wontfix` status. I already implemented some partial functionality for this but during the technical analysis I've found a limitation of Windows that dictates that the can't be more than one Run as command in the context menu.

I could add as many shortcut into the root context menu but there could be only one shortcut with elevated privileges. In addition, there is a recommendation to **not place** any shortcut with elevated privileges. Any application can override it.

In order to keep the functionality of this module consistent, I drop this idea to create shortcuts in the root context menu.

I hope that you still enjoy this module as it is. ✌
