### ISSUE TITLE
How could I add the Windows Terminal Preview?

### ISSUE THREAD

**Issue by AGDholo** [KUTlime/PowerShell-Open-Here-Module#23]
Try `Set-OpenHereShortcut -ShortcutType:WindowsTerminalPreview" but wrong.

**Comment by KUTlime** [comment]
You can't. Windows Terminal Preview is not currently supported. I will have a look at possible support.

**Comment by KUTlime** [comment]
@AGDholo Windows Terminal Preview is opened when it is installed in your system and you try execute `wt`.

You can create shortcut for Windows Terminal by executing `Set-OpenHereShortcut -ShortcutType:WindowsTerminal`.
It will work for Windows Terminal Preview.

Feel free to ask more questions if you need to clarify something.

**Comment by AGDholo** [comment]
Thanks for your great work!
I have tow version, Stable and preview.
There is one stable option display in right click when I exec the `Set-OpenHereShortcut -ShortcutType:WindowsTerminal`.

Is there no way for them to coexist? Or do I need to update the version of the package?

**Comment by KUTlime** [comment]
The thing is that there is (probably) no way how to distinguish between WT (Windows Terminal) and WTP (Windows Terminal Preview).

When you type `wt` in some shell, it will run WTP when it is installed in the system, WT otherwise. I can't find a way how to distinguish between them. I run WT/WTP by Windows PowerShell, because there is no other way how to cover edge cases for WP, e.g. special characters in path or root directories (_C:\, D:\ etc._).

So if we can find a solution how to invoke WT and WTP from the shell, I can make separate shortcuts.

**Comment by KUTlime** [comment]
Hi @AGDholo 
the user @KalleOlaviNiemitalo found the solution for your problem [here](https://github.com/microsoft/terminal/issues/6416#issuecomment-772610393).

**Comment by KalleOlaviNiemitalo** [comment]
My comment about the PackagedCom Registry key applies only to the shell extension that Windows Terminal installs. It does not apply to running `wt.exe` in other ways, like in this code:

<https://github.com/KUTlime/PowerShell-Open-Here-Module/blob/07e7cd49882acafc89c13b3e50f8056b624372ac/OpenHere/OpenHere.psm1#L97-L98>

For that, I think you have two options:

* Advise users to open "App execution aliases" in the Settings app of Windows and select whether to activate the `wt.exe` alias for Windows Terminal or Windows Terminal Preview.
* Alternatively, change the PowerShell code to run `${Env:LOCALAPPDATA}\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe` or `${Env:LOCALAPPDATA}\Microsoft\WindowsApps\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\wt.exe`, rather than plain `wt`. That way, it would not depend on which app execution alias is active.

**Comment by KUTlime** [comment]
@KalleOlaviNiemitalo Thx for clarification!
